-- ============================================================================
-- FLIGHTHUB DATABASE SCHEMA
-- ============================================================================
-- Arquitectura basada en Domain-Driven Design (DDD)
-- 13 dominios independientes con 27 tablas
-- FUID (ULID) como identificador único interno
-- 6 campos de identificación externa en cada tabla
-- ============================================================================

-- ============================================================================
-- DOMINIO: FLIGHT ORCHESTRATOR
-- ============================================================================
-- Responsabilidad: Identificación única de vuelos, gestión del ciclo de vida,
--                  trazabilidad de mensajes
-- ============================================================================

-- Tabla principal de vuelos con información de identificación única
CREATE TABLE fh_flight (
  -- Identificador único permanente (ULID)
  fuid VARCHAR(26) PRIMARY KEY,

  -- 6 Campos de Identificación Externa
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Códigos ICAO adicionales
  airline_designator_icao VARCHAR(4) NOT NULL,
  flight_designator_atc VARCHAR(10) NOT NULL,
  departure_airport_icao VARCHAR(4) NOT NULL,
  departure_airport_orig VARCHAR(3) NOT NULL,
  departure_airport_orig_icao VARCHAR(4) NOT NULL,
  arrival_airport VARCHAR(3) NOT NULL,
  arrival_airport_icao VARCHAR(4) NOT NULL,
  arrival_airport_orig VARCHAR(3) NOT NULL,
  arrival_airport_orig_icao VARCHAR(4) NOT NULL,

  -- Control de estado
  active BOOLEAN NOT NULL DEFAULT true,
  principal BOOLEAN NOT NULL DEFAULT true,
  fuid_new_flight VARCHAR(26) NULL,
  fuid_flight_principal VARCHAR(26) NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_flight
CREATE INDEX idx_fh_flight_operation_date ON fh_flight(operation_date);
CREATE INDEX idx_fh_flight_airline ON fh_flight(airline_designator);
CREATE INDEX idx_fh_flight_designator ON fh_flight(flight_designator);
CREATE INDEX idx_fh_flight_departure ON fh_flight(departure_airport);
CREATE INDEX idx_fh_flight_active ON fh_flight(active);
CREATE INDEX idx_fh_flight_principal ON fh_flight(principal);

-- Registros de procesamiento de vuelos - control de procesamiento de mensajes
CREATE TABLE flight_record (
  -- Identificador
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

  -- Identificación del mensaje
  arinc633message_id VARCHAR(255) NULL,
  flight_identifier VARCHAR(255) NULL,

  -- Control de procesamiento
  attempts INTEGER NOT NULL,
  status INTEGER NOT NULL,
  execution_date DATE NULL,
  comments VARCHAR(255) NULL
);

-- Índices para flight_record
CREATE INDEX idx_flight_record_identifier ON flight_record(flight_identifier);
CREATE INDEX idx_flight_record_status ON flight_record(status);
CREATE INDEX idx_flight_record_execution_date ON flight_record(execution_date);

-- Log completo de todos los mensajes recibidos y procesados
CREATE TABLE fh_message_log (
  -- Identificador
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información del mensaje
  source VARCHAR(50) NOT NULL,     -- 'TELEX', 'AENA', 'CKI'
  message_type VARCHAR(50) NOT NULL,     -- 'MVT', 'ASM', 'CDM'
  message_subtype VARCHAR(50) NULL,         -- 'NEW', 'AA', 'AD'

  -- Contenido
  raw_message JSONB NOT NULL,           -- Mensaje original
  parsed_message JSONB NULL,               -- Mensaje parseado

  -- Estado de procesamiento
  processing_status VARCHAR(20) NOT NULL,     -- PENDING, PROCESSED, FAILED
  processed_at TIMESTAMP NULL,
  error_message TEXT NULL,

  -- Auditoría
  received_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Índices para fh_message_log
CREATE INDEX idx_fh_message_log_fuid ON fh_message_log(fuid);
CREATE INDEX idx_fh_message_log_source_type ON fh_message_log(source, message_type);
CREATE INDEX idx_fh_message_log_status ON fh_message_log(processing_status);
CREATE INDEX idx_fh_message_log_received ON fh_message_log(received_at);

-- ============================================================================
-- DOMINIO: RESOURCES
-- ============================================================================
-- Responsabilidad: Gestión de recursos aeroportuarios (terminales, puertas,
--                  stands, pistas, cintas, mostradores)
-- ============================================================================

-- Recursos aeroportuarios asignados al vuelo
CREATE TABLE fh_resource_airport (
  -- Identificador único
  fuid VARCHAR(26) PRIMARY KEY REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Recursos de Salida
  departure_terminal_zone VARCHAR NULL,
  departure_terminal VARCHAR NULL,
  departure_stand VARCHAR NULL,
  departure_runway VARCHAR NULL,
  departure_checkin_counter_first VARCHAR NULL,
  departure_checkin_counter_last VARCHAR NULL,
  departure_checkin_counter_type VARCHAR NULL,
  departure_boarding_zone VARCHAR NULL,
  departure_boarding_gate VARCHAR NULL,
  departure_boarding_gate_2 VARCHAR NULL,
  departure_bag_belt VARCHAR NULL,
  departure_bag_belt_status VARCHAR NULL,

  -- Recursos de Llegada
  arrival_terminal_zone VARCHAR NULL,
  arrival_terminal VARCHAR NULL,
  arrival_stand VARCHAR NULL,
  arrival_runway VARCHAR NULL,
  arrival_hall VARCHAR NULL,
  arrival_gate VARCHAR NULL,
  arrival_bag_belt VARCHAR NULL,
  arrival_bag_belt_2 VARCHAR NULL,
  arrival_bag_belt_status VARCHAR NULL,
  arrival_bag_claim_unit_code VARCHAR NULL,
  arrival_bag_claim_unit_status VARCHAR NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_resource_airport
CREATE INDEX idx_fh_resource_departure_gate ON fh_resource_airport(departure_boarding_gate);
CREATE INDEX idx_fh_resource_departure_stand ON fh_resource_airport(departure_stand);
CREATE INDEX idx_fh_resource_arrival_gate ON fh_resource_airport(arrival_gate);
CREATE INDEX idx_fh_resource_arrival_stand ON fh_resource_airport(arrival_stand);

-- ============================================================================
-- DOMINIO: TIMELINE
-- ============================================================================
-- Responsabilidad: Todos los tiempos operacionales del vuelo (salida, llegada,
--                  CDM, embarque, puertas)
-- ============================================================================

-- Tiempos de salida del vuelo
CREATE TABLE fh_timeline_departure (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Variación horaria
  departure_time_variation VARCHAR NOT NULL,
  departure_time_variation_orig VARCHAR NOT NULL,

  -- Tiempos programados
  departure_time_scheduled TIMESTAMP NOT NULL,

  -- Tiempos estimados
  departure_time_estimated TIMESTAMP NOT NULL,
  off_blocks_time_estimated TIMESTAMP NOT NULL,
  taxi_out_time_estimated NUMERIC NULL,
  takeoff_time_estimated TIMESTAMP NOT NULL,

  -- Tiempos reales
  departure_time_actual TIMESTAMP NULL,
  off_blocks_time_actual TIMESTAMP NULL,
  taxi_out_time_actual NUMERIC NULL,
  takeoff_time_actual TIMESTAMP NULL,

  -- Tiempos de puertas y cabina
  cabin_door_close_estimated TIMESTAMP NOT NULL,
  cabin_door_close_actual TIMESTAMP NULL,
  cargo_door_close_actual TIMESTAMP NULL,

  -- Tiempos de embarque
  departure_boarding_gate_start_time TIMESTAMP NULL,
  departure_boarding_gate_end_time TIMESTAMP NULL,
  departure_boarding_gate2_start_time TIMESTAMP NULL,
  departure_boarding_gate2_end_time TIMESTAMP NULL,

  -- Tiempos de equipaje
  departure_bag_belt_start_time TIMESTAMP NULL,
  departure_bag_belt_end_time TIMESTAMP NULL,

  -- Tiempos de preparación
  ready_cabin_time_estimated TIMESTAMP NULL,
  ready_cabin_time_actual TIMESTAMP NULL,
  ready_maintenance_time_actual TIMESTAMP NULL,
  ready_parking_time_actual TIMESTAMP NULL,
  next_info_departure_time_actual TIMESTAMP NULL,

  -- Block time
  block_time_min_estimated NUMERIC NOT NULL,
  block_time_min_actual NUMERIC NULL,
  block_time_min_estimated_orig NUMERIC NOT NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL,

  UNIQUE(fuid)
);

-- Índices para fh_timeline_departure
CREATE INDEX idx_fh_timeline_departure_scheduled ON fh_timeline_departure(departure_time_scheduled);
CREATE INDEX idx_fh_timeline_departure_actual ON fh_timeline_departure(departure_time_actual);

-- Tiempos de llegada del vuelo
CREATE TABLE fh_timeline_arrival (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Variación horaria
  arrival_time_variation VARCHAR NOT NULL,
  arrival_time_variation_orig VARCHAR NOT NULL,

  -- Tiempos programados
  arrival_time_scheduled TIMESTAMP NOT NULL,

  -- Tiempos estimados
  arrival_time_estimated TIMESTAMP NOT NULL,
  landing_time_estimated TIMESTAMP NOT NULL,
  on_blocks_time_estimated TIMESTAMP NOT NULL,
  taxi_in_time_estimated NUMERIC NULL,

  -- Tiempos reales
  arrival_time_actual TIMESTAMP NULL,
  landing_time_actual TIMESTAMP NULL,
  on_blocks_time_actual TIMESTAMP NULL,
  taxi_in_time_actual NUMERIC NULL,

  -- Tiempos de puertas
  cabin_door_open_estimated TIMESTAMP NOT NULL,
  cabin_door_open_actual TIMESTAMP NULL,
  cargo_door_open_actual TIMESTAMP NULL,

  -- Tiempos de cintas equipaje
  arrival_bag_belt_start_time TIMESTAMP NULL,
  arrival_bag_belt_end_time TIMESTAMP NULL,
  arrival_bag_belt2_start_time TIMESTAMP NULL,
  arrival_bag_belt2_end_time TIMESTAMP NULL,
  arrival_bag_claim_unit_start_time TIMESTAMP NULL,
  arrival_bag_claim_unit_end_time TIMESTAMP NULL,

  -- Trip time
  trip_time_min_estimated NUMERIC NOT NULL,
  trip_time_min_actual NUMERIC NULL,
  trip_time_min_estimated_orig NUMERIC NOT NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL,

  UNIQUE(fuid)
);

-- Índices para fh_timeline_arrival
CREATE INDEX idx_fh_timeline_arrival_scheduled ON fh_timeline_arrival(arrival_time_scheduled);
CREATE INDEX idx_fh_timeline_arrival_actual ON fh_timeline_arrival(arrival_time_actual);

-- Tiempos CDM (Collaborative Decision Making) específicos
CREATE TABLE fh_timeline_cdm (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Off-Blocks Times (CDM)
  off_blocks_time_scheduled_cdm TIMESTAMP NULL,
  off_blocks_time_estimated_cdm TIMESTAMP NULL,
  off_blocks_time_target_cdm TIMESTAMP NULL,
  off_blocks_time_actual_cdm TIMESTAMP NULL,

  -- Taxi Times (CDM)
  taxi_out_time_estimated_cdm NUMERIC NULL,
  taxi_out_time_actual_cdm NUMERIC NULL,
  taxi_in_time_estimated_cdm NUMERIC NULL,
  taxi_in_time_actual_cdm NUMERIC NULL,

  -- Take-Off Times (CDM)
  takeoff_time_estimated_cdm TIMESTAMP NULL,
  takeoff_time_calculated_cdm TIMESTAMP NULL,
  takeoff_time_target_cdm TIMESTAMP NULL,
  takeoff_time_actual_cdm TIMESTAMP NULL,

  -- Landing Times (CDM)
  landing_time_estimated_cdm TIMESTAMP NULL,
  landing_time_target_cdm TIMESTAMP NULL,
  landing_time_actual_cdm TIMESTAMP NULL,

  -- On-Blocks Times (CDM)
  on_blocks_time_scheduled_cdm TIMESTAMP NULL,
  on_blocks_time_estimated_cdm TIMESTAMP NULL,
  on_blocks_time_actual_cdm TIMESTAMP NULL,

  -- Turnaround Times (CDM)
  turnaround_time_scheduled_cdm TIMESTAMP NULL,
  turnaround_time_estimated_cdm TIMESTAMP NULL,
  turnaround_time_minimum_cdm TIMESTAMP NULL,
  turnaround_time_actual_cdm TIMESTAMP NULL,

  -- Ground Handling Times (CDM)
  ground_handling_time_actual_cdm TIMESTAMP NULL,
  ground_handling_start_time_cdm TIMESTAMP NULL,
  ground_handling_end_time_cdm TIMESTAMP NULL,

  -- Startup Times (CDM)
  startup_request_time_actual_cdm TIMESTAMP NULL,
  startup_approval_time_target_cdm TIMESTAMP NULL,
  startup_approval_time_actual_cdm TIMESTAMP NULL,

  -- De-icing Times (CDM)
  deicing_time_estimated_cdm TIMESTAMP NULL,
  deicing_time_actual_cdm TIMESTAMP NULL,
  deicing_ready_time_estimated_cdm TIMESTAMP NULL,
  deicing_ready_time_actual_cdm TIMESTAMP NULL,
  deicing_start_time_estimated_cdm TIMESTAMP NULL,
  deicing_start_time_actual_cdm TIMESTAMP NULL,
  deicing_end_time_estimated_cdm TIMESTAMP NULL,
  deicing_end_time_actual_cdm TIMESTAMP NULL,

  -- Ready Departure Time (CDM)
  ready_departure_time_actual_cdm TIMESTAMP NULL,

  -- Boarding Start Time (CDM)
  start_boarding_time_actual_cdm TIMESTAMP NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL,

  UNIQUE(fuid)
);

-- Índices para fh_timeline_cdm
CREATE INDEX idx_fh_timeline_cdm_tobt ON fh_timeline_cdm(off_blocks_time_target_cdm);
CREATE INDEX idx_fh_timeline_cdm_tsat ON fh_timeline_cdm(startup_approval_time_target_cdm);

-- Tiempos de check-in (CI, CL, CC) y sus variantes WAB
CREATE TABLE fh_timeline_checkin (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Check-in CI (inicial)
  checkin_ci_time_actual TIMESTAMP NULL,

  -- Check-in CL (intermedio)
  checkin_cl_time_actual TIMESTAMP NULL,

  -- Check-in CC (final)
  checkin_cc_time_actual TIMESTAMP NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL,

  UNIQUE(fuid)
);

-- ============================================================================
-- DOMINIO: DELAYS
-- ============================================================================
-- Responsabilidad: Gestión de retrasos del vuelo con sus códigos y tiempos
-- ============================================================================

-- Información de retrasos del vuelo (hasta 4 retrasos diferentes)
CREATE TABLE fh_delay (
  -- Identificador único
  fuid VARCHAR(26) PRIMARY KEY REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Retraso 1
  delay_type_1 VARCHAR NOT NULL,     -- SCD, DEP
  delay_number_1 VARCHAR NOT NULL,
  delay_code_1 VARCHAR NOT NULL,
  delay_group_code_1 VARCHAR NOT NULL,
  delay_mins_1 NUMERIC NOT NULL,
  delay_comments_1 VARCHAR NOT NULL,

  -- Retraso 2
  delay_type_2 VARCHAR NULL,
  delay_number_2 VARCHAR NULL,
  delay_code_2 VARCHAR NULL,
  delay_group_code_2 VARCHAR NULL,
  delay_mins_2 NUMERIC NULL,
  delay_comments_2 VARCHAR NULL,

  -- Retraso 3
  delay_type_3 VARCHAR NULL,
  delay_number_3 VARCHAR NULL,
  delay_code_3 VARCHAR NULL,
  delay_group_code_3 VARCHAR NULL,
  delay_mins_3 NUMERIC NULL,
  delay_comments_3 VARCHAR NULL,

  -- Retraso 4
  delay_type_4 VARCHAR NULL,
  delay_number_4 VARCHAR NULL,
  delay_code_4 VARCHAR NULL,
  delay_group_code_4 VARCHAR NULL,
  delay_mins_4 NUMERIC NULL,
  delay_comments_4 VARCHAR NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_delay
CREATE INDEX idx_fh_delay_code_1 ON fh_delay(delay_code_1);
CREATE INDEX idx_fh_delay_mins ON fh_delay(delay_mins_1, delay_mins_2, delay_mins_3, delay_mins_4);

-- Tabla alternativa normalizada para retrasos (opcional)
CREATE TABLE fh_delay_detail (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información del retraso
  delay_sequence INTEGER NOT NULL,         -- 1, 2, 3, 4
  delay_type VARCHAR NOT NULL,         -- SCD, DEP
  delay_number VARCHAR NOT NULL,
  delay_code VARCHAR NOT NULL,
  delay_group_code VARCHAR NOT NULL,
  delay_minutes NUMERIC NOT NULL,
  delay_comments VARCHAR NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_delay_detail
CREATE INDEX idx_fh_delay_detail_fuid ON fh_delay_detail(fuid);
CREATE INDEX idx_fh_delay_detail_code ON fh_delay_detail(delay_code);
CREATE INDEX idx_fh_delay_detail_sequence ON fh_delay_detail(delay_sequence);

-- ============================================================================
-- DOMINIO: CREW
-- ============================================================================
-- Responsabilidad: Información de tripulación del vuelo
-- ============================================================================

-- Asignación de tripulación técnica y de cabina
CREATE TABLE fh_crew_assignment (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información de tripulación técnica (Cockpit)
  cockpit_crew_count INTEGER NULL,
  cockpit_employer VARCHAR NULL,

  -- Información de tripulación de cabina
  cabin_crew_count INTEGER NULL,
  cabin_employer VARCHAR NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_crew_assignment
CREATE INDEX idx_fh_crew_assignment_fuid ON fh_crew_assignment(fuid);

-- ============================================================================
-- DOMINIO: ALERTS
-- ============================================================================
-- Responsabilidad: Alertas, alarmas y situaciones especiales (desvíos, retornos)
-- ============================================================================

-- Alarmas operacionales del vuelo
CREATE TABLE fh_alert_alarm (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información de la alarma
  alarm_code VARCHAR(20) NULL,
  alarm_text TEXT NULL,
  alarm_severity VARCHAR(20) NULL,        -- INFO, WARNING, CRITICAL

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_alert_alarm
CREATE INDEX idx_fh_alert_alarm_fuid ON fh_alert_alarm(fuid);
CREATE INDEX idx_fh_alert_alarm_code ON fh_alert_alarm(alarm_code);
CREATE INDEX idx_fh_alert_alarm_severity ON fh_alert_alarm(alarm_severity);

-- Información de desvíos, retornos o vuelos frustrados
CREATE TABLE fh_alert_diversion (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información del desvío
  diversion_type VARCHAR(20) NULL,        -- DIVERSION, RETURN, ABORTED
  diversion_airport VARCHAR(3) NULL,
  diversion_airport_icao VARCHAR(4) NULL,
  diversion_code VARCHAR(20) NULL,
  diversion_reason TEXT NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_alert_diversion
CREATE INDEX idx_fh_alert_diversion_fuid ON fh_alert_diversion(fuid);
CREATE INDEX idx_fh_alert_diversion_airport ON fh_alert_diversion(diversion_airport);

-- ============================================================================
-- DOMINIO: PASSENGERS
-- ============================================================================
-- Responsabilidad: Todo lo relacionado con pasajeros, capacidad, reservas,
--                  facturación, embarque
-- ============================================================================

-- Resumen general de pasajeros (totales y desglose por tipo)
CREATE TABLE fh_pax_summary (
  -- Identificador único
  fuid VARCHAR(26) PRIMARY KEY REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Totales generales
  config_total NUMERIC NOT NULL DEFAULT 0,
  capacity_total NUMERIC NOT NULL DEFAULT 0,
  availability_total NUMERIC NOT NULL DEFAULT 0,
  load_factor_total NUMERIC NOT NULL DEFAULT 0,
  booked_pax_total NUMERIC NOT NULL DEFAULT 0,
  checked_pax_total NUMERIC NOT NULL DEFAULT 0,
  boarded_pax_total NUMERIC NOT NULL DEFAULT 0,
  forecast_pax_total NUMERIC NOT NULL DEFAULT 0,

  -- Por conexión
  inbound_booked_pax_total NUMERIC NOT NULL DEFAULT 0,
  outbound_booked_pax_total NUMERIC NOT NULL DEFAULT 0,

  -- Por tipo de pasajero
  adult_pax_total NUMERIC NOT NULL DEFAULT 0,
  male_pax_total NUMERIC NOT NULL DEFAULT 0,
  female_pax_total NUMERIC NOT NULL DEFAULT 0,
  no_gender_pax_total NUMERIC NOT NULL DEFAULT 0,
  child_pax_total NUMERIC NOT NULL DEFAULT 0,
  infant_pax_total NUMERIC NOT NULL DEFAULT 0,

  -- Pasajeros especiales
  pad_pax_total NUMERIC NOT NULL DEFAULT 0,
  dhc_pax_total NUMERIC NOT NULL DEFAULT 0,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_pax_summary
CREATE INDEX idx_fh_pax_summary_booked ON fh_pax_summary(booked_pax_total);
CREATE INDEX idx_fh_pax_summary_checked ON fh_pax_summary(checked_pax_total);
CREATE INDEX idx_fh_pax_summary_boarded ON fh_pax_summary(boarded_pax_total);

-- Información de pasajeros desglosada por cabina (Business, Premium, Turista)
CREATE TABLE fh_pax_cabin (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Identificación de cabina
  cabin_code VARCHAR(10) NOT NULL,    -- JC, W, Y
  cabin_name VARCHAR(50) NULL,        -- Business, Premium, Turista

  -- Configuración y capacidad
  config_cabin NUMERIC NOT NULL DEFAULT 0,
  capacity_cabin NUMERIC NOT NULL DEFAULT 0,
  availability_cabin NUMERIC NOT NULL DEFAULT 0,
  load_factor_cabin NUMERIC NOT NULL DEFAULT 0,

  -- Contadores de pasajeros
  booked_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  checked_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  boarded_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  forecast_pax_cabin NUMERIC NOT NULL DEFAULT 0,

  -- Por conexión
  inbound_booked_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  outbound_booked_pax_cabin NUMERIC NOT NULL DEFAULT 0,

  -- Check-in por evento (CI, CL, CC)
  checked_in_pax_total_ci NUMERIC NOT NULL DEFAULT 0,
  checked_in_pax_total_cl NUMERIC NOT NULL DEFAULT 0,
  checked_in_pax_total_cc NUMERIC NOT NULL DEFAULT 0,
  checked_in_infants_total_ci NUMERIC NOT NULL DEFAULT 0,
  checked_in_infants_total_cl NUMERIC NOT NULL DEFAULT 0,
  checked_in_infants_total_cc NUMERIC NOT NULL DEFAULT 0,
  checked_in_pax_cabin_ci NUMERIC NOT NULL DEFAULT 0,
  checked_in_pax_cabin_cl NUMERIC NOT NULL DEFAULT 0,
  checked_in_pax_cabin_cc NUMERIC NOT NULL DEFAULT 0,

  -- Por tipo de pasajero
  adult_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  male_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  female_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  no_gender_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  child_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  infant_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  pad_pax_cabin NUMERIC NOT NULL DEFAULT 0,
  dhc_pax_cabin NUMERIC NOT NULL DEFAULT 0,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL,

  UNIQUE(fuid, cabin_code)
);

-- Índices para fh_pax_cabin
CREATE INDEX idx_fh_pax_cabin_cabin_code ON fh_pax_cabin(cabin_code);

-- Pasajeros con necesidades especiales o categorías particulares
CREATE TABLE fh_pax_special (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Categoría del pasajero especial
  category_code VARCHAR(10) NOT NULL,    -- WCHC, WCHR, WCHS, UM, etc.
  category_name VARCHAR(100) NULL,
  cabin_class VARCHAR(20) NULL,        -- cabin1, cabin2, cabin3
  quantity INTEGER NOT NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_pax_special
CREATE INDEX idx_fh_pax_special_fuid ON fh_pax_special(fuid);
CREATE INDEX idx_fh_pax_special_category ON fh_pax_special(category_code);

-- ============================================================================
-- DOMINIO: BAGGAGE
-- ============================================================================
-- Responsabilidad: Equipaje, carga y correo
-- ============================================================================

-- Resumen de equipaje del vuelo
CREATE TABLE fh_bag_summary (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información de equipaje (de LDM u otras fuentes)
  total_bags INTEGER NULL,
  total_bag_weight_kg INTEGER NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_bag_summary
CREATE INDEX idx_fh_bag_summary_fuid ON fh_bag_summary(fuid);

-- Resumen de carga y correo del vuelo
CREATE TABLE fh_bag_cargo (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Pesos de carga (kg)
  cargo_weight_kg INTEGER NULL,
  additional_cargo_weight_kg INTEGER NULL,
  total_cargo_weight_kg INTEGER NULL,

  -- Pesos de correo (kg)
  mail_weight_kg INTEGER NULL,
  additional_mail_weight_kg INTEGER NULL,
  total_mail_weight_kg INTEGER NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_bag_cargo
CREATE INDEX idx_fh_bag_cargo_fuid ON fh_bag_cargo(fuid);

-- Ítems individuales de carga especial (AVI, DGR, HUM, etc.)
CREATE TABLE fh_bag_cargo_item (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información del ítem
  item_name VARCHAR(100) NOT NULL,   -- AVI, DGR, HUM, etc.
  item_value NUMERIC NULL,
  item_unit VARCHAR(20) NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_bag_cargo_item
CREATE INDEX idx_fh_bag_cargo_item_fuid ON fh_bag_cargo_item(fuid);
CREATE INDEX idx_fh_bag_cargo_item_name ON fh_bag_cargo_item(item_name);

-- ============================================================================
-- DOMINIO: FUEL
-- ============================================================================
-- Responsabilidad: Combustible, repostaje, planificación de fuel
-- ============================================================================

-- Resumen de combustible del vuelo
CREATE TABLE fh_fuel_summary (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Pesos de combustible (kg)
  total_fuel_weight_kg INTEGER NULL,
  taxi_fuel_weight_kg INTEGER NULL,
  trip_fuel_weight_kg INTEGER NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_fuel_summary
CREATE INDEX idx_fh_fuel_summary_fuid ON fh_fuel_summary(fuid);

-- Combustible al aceptar aeronave
CREATE TABLE fh_fuel_accept_aircraft (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Combustibles (kg)
  arrival_fuel_kg INTEGER NULL,
  remaining_fuel_kg INTEGER NULL,
  fuel_tipping_kg INTEGER NULL,
  depart_fuel_kg INTEGER NULL,
  calculated_planned_uplift_kg INTEGER NULL,
  required_block_fuel_kg INTEGER NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_fuel_accept_aircraft
CREATE INDEX idx_fh_fuel_accept_aircraft_fuid ON fh_fuel_accept_aircraft(fuid);

-- Combustible al cerrar vuelo
CREATE TABLE fh_fuel_close_flight (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Combustibles (kg)
  arrival_fuel_kg INTEGER NULL,
  remaining_fuel_kg INTEGER NULL,
  fuel_tipping_kg INTEGER NULL,
  depart_fuel_kg INTEGER NULL,
  calculated_planned_uplift_kg INTEGER NULL,
  required_block_fuel_kg INTEGER NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_fuel_close_flight
CREATE INDEX idx_fh_fuel_close_flight_fuid ON fh_fuel_close_flight(fuid);

-- Eventos de repostaje
CREATE TABLE fh_fuel_event (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Tipo de evento
  event_type VARCHAR(50) NOT NULL,    -- ACCEPT_AIRCRAFT, CLOSE_FLIGHT

  -- Información del repostaje
  measurement_system VARCHAR(20) NULL,        -- metric, imperial, us
  supplier VARCHAR(100) NULL,
  vendor VARCHAR(100) NULL,
  invoice_number VARCHAR(50) NULL,

  -- Tipo y densidad del combustible
  fuel_type VARCHAR(20) NULL,        -- JET A1
  density NUMERIC(10,3) NULL,
  density_unit VARCHAR(20) NULL,

  -- Cantidad repostada
  actual_uplift NUMERIC(10,2) NULL,
  actual_uplift_unit VARCHAR(20) NULL,

  -- Cambios y razones
  new_fuel_kg INTEGER NULL,
  reason TEXT NULL,
  reduce_note TEXT NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_fuel_event
CREATE INDEX idx_fh_fuel_event_fuid ON fh_fuel_event(fuid);
CREATE INDEX idx_fh_fuel_event_type ON fh_fuel_event(event_type);

-- ============================================================================
-- DOMINIO: AIRCRAFT
-- ============================================================================
-- Responsabilidad: Información de aeronaves, configuraciones, asignaciones
-- ============================================================================

-- Información de la aeronave asignada al vuelo
CREATE TABLE fh_aircraft_info (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información del propietario y operador
  aircraft_owner VARCHAR NOT NULL,
  cockpit_employer VARCHAR NOT NULL,
  cabin_employer VARCHAR NOT NULL,

  -- Tipo y configuración
  aircraft_type VARCHAR NOT NULL,
  aircraft_subtype VARCHAR NOT NULL,
  aircraft_config VARCHAR NOT NULL,
  aircraft_version VARCHAR NULL,
  aircraft_registration VARCHAR NULL,
  aircraft_registration_first VARCHAR NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_aircraft_info
CREATE INDEX idx_fh_aircraft_info_fuid ON fh_aircraft_info(fuid);
CREATE INDEX idx_fh_aircraft_info_registration ON fh_aircraft_info(aircraft_registration);
CREATE INDEX idx_fh_aircraft_info_type ON fh_aircraft_info(aircraft_type);

-- Registro maestro de aeronaves (catálogo)
CREATE TABLE fh_aircraft_registry (
  -- Identificador único
  id UUID PRIMARY KEY,
  tail_number VARCHAR(10) UNIQUE NOT NULL,

  -- Tipo de aeronave
  aircraft_type VARCHAR(10) NOT NULL,
  aircraft_subtype VARCHAR(20) NULL,
  manufacturer VARCHAR(50) NULL,
  serial_number VARCHAR(50) NULL,

  -- Propietario
  airline_owner VARCHAR(3) NULL,
  registration_country VARCHAR(2) NULL,

  -- Estado operacional
  operational_status VARCHAR(20) NULL,
  in_service_date DATE NULL,
  out_of_service_date DATE NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Índices para fh_aircraft_registry
CREATE INDEX idx_fh_aircraft_registry_type ON fh_aircraft_registry(aircraft_type);
CREATE INDEX idx_fh_aircraft_registry_owner ON fh_aircraft_registry(airline_owner);

-- ============================================================================
-- DOMINIO: SCHEDULES
-- ============================================================================
-- Responsabilidad: Programación de vuelos, información SSIM
-- ============================================================================

-- Información de programación y servicio del vuelo
CREATE TABLE fh_schedule_info (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Tipo de servicio
  service_type_code VARCHAR NOT NULL,
  service_type_desc VARCHAR NOT NULL,

  -- Estado del vuelo
  status_code VARCHAR NOT NULL DEFAULT 'PDEP',
  status_desc VARCHAR NOT NULL DEFAULT 'Predeparture',

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_schedule_info
CREATE INDEX idx_fh_schedule_info_fuid ON fh_schedule_info(fuid);
CREATE INDEX idx_fh_schedule_info_status ON fh_schedule_info(status_code);

-- ============================================================================
-- DOMINIO: ONWARD FLIGHTS
-- ============================================================================
-- Responsabilidad: Relación entre un vuelo de llegada (inbound) y sus vuelos
--                  de continuación (onward), ya sea para pasajeros en conexión
--                  o simplemente para mapear continuidad operacional
-- ============================================================================

-- Información del vuelo siguiente conectado (onward flight)
CREATE TABLE fh_onward_flight (
  -- Identificador único
  id UUID PRIMARY KEY,

  -- Vuelo de llegada (inbound)
  inbound_fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación del vuelo inbound
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Vuelo siguiente / de continuación (onward)
  onward_airline_designator VARCHAR(3) NOT NULL,
  onward_flight_designator VARCHAR(10) NOT NULL,
  onward_operation_date DATE NOT NULL,
  onward_operation_day VARCHAR(2),

  -- Metadatos y clasificaciones
  connection_type VARCHAR(20),              -- direct, interline, codeshare, etc.
  min_connection_time_minutes INTEGER,      -- MCT opcional, para planificación
  turnaround_time_minutes INTEGER,          -- opcional si se usa también para tiempos entre vuelos

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_onward_flight
CREATE INDEX idx_fh_onward_flight_inbound ON fh_onward_flight(inbound_fuid);
CREATE INDEX idx_fh_onward_flight_onward ON fh_onward_flight(onward_airline_designator, onward_flight_designator, onward_operation_date);

-- ============================================================================
-- DOMINIO: CODESHARE
-- ============================================================================
-- Responsabilidad: Información de vuelos compartidos
-- ============================================================================

-- Información de vuelos codeshare (compartidos)
CREATE TABLE fh_codeshare_info (
  -- Identificador único
  id UUID PRIMARY KEY,
  fuid VARCHAR(26) NOT NULL REFERENCES fh_flight(fuid),

  -- 6 Campos de Identificación
  operation_date DATE NOT NULL,
  flight_designator VARCHAR(10) NOT NULL,
  operational_suffix VARCHAR(3) NOT NULL DEFAULT '',
  airline_designator VARCHAR(3) NOT NULL,
  departure_airport VARCHAR(3) NOT NULL,
  departure_number INTEGER NOT NULL DEFAULT 1,

  -- Información de codeshare
  codeshare_indicator VARCHAR(1) NULL,         -- P (Principal), S (Secondary)
  codeshare_principal_flight_id VARCHAR NULL,
  codeshare_principal_flight VARCHAR NULL,
  codeshare_secondary_flights VARCHAR NULL,

  -- Auditoría
  created_at TIMESTAMP NOT NULL,
  created_by VARCHAR NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  updated_by VARCHAR NOT NULL
);

-- Índices para fh_codeshare_info
CREATE INDEX idx_fh_codeshare_info_fuid ON fh_codeshare_info(fuid);
CREATE INDEX idx_fh_codeshare_info_indicator ON fh_codeshare_info(codeshare_indicator);

-- ============================================================================
-- COMENTARIOS FINALES
-- ============================================================================
--
-- Este schema SQL representa la arquitectura completa de FlightHub basada en
-- Domain-Driven Design (DDD) con 13 dominios de negocio independientes.
--
-- CARACTERÍSTICAS PRINCIPALES:
-- - 27 tablas organizadas en 13 dominios
-- - FUID (ULID) como identificador único interno
-- - 6 campos de identificación externa replicados en cada tabla
-- - Sin JOINs necesarios (cada tabla es independiente)
-- - Escalabilidad independiente por dominio
-- - Prefijos consistentes (fh_*)
-- - Campos en snake_case
-- - Auditoría completa en todas las tablas
--
-- DOMINIOS:
-- 1. Flight Orchestrator (3 tablas) - Identificación y enrutamiento
-- 2. Resources (1 tabla) - Recursos aeroportuarios
-- 3. Timeline (4 tablas) - Tiempos operacionales
-- 4. Delays (1-2 tablas) - Retrasos
-- 5. Crew (1 tabla) - Tripulación
-- 6. Alerts (2 tablas) - Alarmas y desvíos
-- 7. Passengers (3 tablas) - Pasajeros y cabinas
-- 8. Baggage (3 tablas) - Equipaje y carga
-- 9. Fuel (4 tablas) - Combustible
-- 10. Aircraft (2 tablas) - Aeronaves
-- 11. Schedules (1 tabla) - Programación
-- 12. Onward Flights (1 tabla) - Vuelos de continuación
-- 13. Codeshare (1 tabla) - Vuelos compartidos
--
-- ============================================================================
